# Generated by Django 3.2.15 on 2023-09-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Happyshopaholic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField(blank=True, verbose_name='Post_id')),
                ('text', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Текст')),
                ('photo_list', models.TextField(blank=True, max_length=100000, null=True, verbose_name='Список Фото')),
                ('is_sent', models.BooleanField(blank=True, default=False, null=True, verbose_name='Отправлено')),
            ],
            options={
                'verbose_name': 'Данные из ВК',
                'verbose_name_plural': 'Данные из ВК',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('user_id', models.IntegerField(blank=True, verbose_name='user_id')),
                ('username', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Username')),
                ('first_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='First_name')),
                ('last_name', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Last_name')),
                ('phone_number', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Phone')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('size', models.CharField(blank=True, choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('4', '4'), ('4.5', '4.5'), ('5', '5'), ('5.5', '5.5'), ('6', '6'), ('6.5', '6.5'), ('7', '7'), ('7.5', '7.5'), ('8', '8'), ('8.5', '8.5'), ('9', '9'), ('9.5', '9.5'), ('10', '10'), ('10.5', '10.5'), ('11', '11'), ('11.5', '11.5'), ('12', '12'), ('12.5', '12.5'), ('13', '13'), ('13.5', '13.5'), ('14', '14'), ('14.5', '14.5'), ('15', '15'), ('15.5', '15.5'), ('16', '16')], max_length=20, null=True, verbose_name='Размер')),
                ('amount', models.IntegerField(blank=True, null=True, verbose_name='Кол-во')),
                ('price', models.CharField(blank=True, max_length=500, null=True, verbose_name='Цена')),
                ('free_order', models.CharField(blank=True, max_length=500, null=True, verbose_name='Заказ в свободной форме')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
