# Generated by Django 3.2.15 on 2023-09-21 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='happyshopaholic',
            table='happyshopaholic',
        ),
    ]
