# Generated by Django 3.2.15 on 2023-09-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bot'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_admin_id', models.CharField(max_length=1000, verbose_name='Admin id')),
            ],
            options={
                'verbose_name': 'Настройки Проекта',
                'verbose_name_plural': 'Настройки Проекта',
            },
        ),
    ]
