# Generated by Django 3.2.15 on 2023-09-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_adminsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_ordered',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Оформление Завершено'),
        ),
    ]
