# Generated by Django 3.2.15 on 2023-09-21 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_is_ordered'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 21, 14, 14, 29, 603905, tzinfo=utc), verbose_name='Дата и время заказа'),
        ),
    ]
