# Generated by Django 4.2.5 on 2023-09-22 07:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_user_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fio',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 22, 7, 39, 32, 677997, tzinfo=datetime.timezone.utc), verbose_name='Дата и время заказа'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='URL фото из TG'),
        ),
    ]
